### ISSUE TITLE
Leer, importante!

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#105]
Chicos  debido a que el proyecto integrador prácticamente lo tenemos terminado, esta semana cada uno puede elegir que tarea hacer para aportar al grupo, ya sea con las clases semanales de node, JS, Python o Java. Como también con los readmes o detalles del grupo o del proyecto. Cuando elijan una tarea escriban en su tarjeta que es lo que van a hacer. Cualquier duda escríbanme. Puede que a algunos les asigne el trabajo yo

**Comment by dwc1970** [comment]
Hola a todos 
 
Cierro el scrum de esta semana y el ultimo scrum de la tecnicatura .....
