### ISSUE TITLE
E-commerce, Abel

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#12]
Chicos este ítem es para decirles que vayan pensando y buscando imágenes de los diferentes tipos de artículos que crean que podemos vender en el E-commerce, el Dante creo un repo en donde subir las imágenes, recuerden que tienen el wiki y el foro. Mucha suerte y cualquier cosa me preguntan

**Comment by Abelino537** [comment]
Bueno dale, Te aviso cuando termine mi actividad

**Comment by Abelino537** [comment]
Ya subi 30 imagenes de productos en el repositorio del proyecto, revisalas si estan bien

**Comment by JereRiquero** [comment]
Perfecto Abel
