### ISSUE TITLE
E-commerce, Lucas

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#13]
Chicos este ítem es para decirles que vayan pensando y buscando imágenes de los diferentes tipos de artículos que crean que podemos vender en el E-commerce, el Dante creo un repo en donde subir las imágenes, recuerden que tienen el wiki y el foro. Mucha suerte y cualquier cosa me preguntan

**Comment by LucasSalinas** [comment]
Subidas las imagenes de la categoria de accesorios...
