### ISSUE TITLE
E-commerce, Andres

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#16]
Chicos este ítem es para decirles que vayan pensando y buscando imágenes de los diferentes tipos de artículos que crean que podemos vender en el E-commerce, el Dante creo un repo en donde subir las imágenes, recuerden que tienen el wiki y el foro. Mucha suerte y cualquier cosa me preguntan

**Comment by andreswinck** [comment]
Aporto con imagenes de los simpsons que m parecen interesantes para armar remeras geek ya que son de personajes de Breaking Bad y Game of thrones

**Comment by andreswinck** [comment]
Agrego Logo de la Web al Readme del proyecto integrador

**Comment by JereRiquero** [comment]
Okey, excelente trabajo Andres
