### ISSUE TITLE
E-commerce, Dario

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#17]
Chicos este ítem es para decirles que vayan pensando y buscando imágenes de los diferentes tipos de artículos que crean que podemos vender en el E-commerce, el Dante creo un repo en donde subir las imágenes, recuerden que tienen el wiki y el foro. Mucha suerte y cualquier cosa me preguntan

**Comment by dwc1970** [comment]
Jere, cargue la Leccion 1 de NodesJS y también las imagenes para el proyecto de E-comerce

**Comment by JereRiquero** [comment]
Perfecto Dario
