### ISSUE TITLE
E-commerce, Dante

### ISSUE THREAD

**Issue by JereRiquero** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#19]
Chicos este ítem es para decirles que vayan pensando y buscando imágenes de los diferentes tipos de artículos que crean que podemos vender en el E-commerce, el Dante creo un repo en donde subir las imágenes, recuerden que tienen el wiki y el foro. Mucha suerte y cualquier cosa me preguntan

**Comment by mzadante** [comment]
dale jere genial

**Comment by mzadante** [comment]
hola Jere ya subi y cree en la carpeta imagenes la categoria de Comics y deje 30 portadas de comics para el ecomerce, abrazo

**Comment by JereRiquero** [comment]
Excelente Dante
