### ISSUE TITLE
Bienvenidos

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#2]
Hola muchachos bueno en este scrum la tarea seria cargar en cada carpeta lo visto en la semana por el profe Ariel, ya sea de python,
Java Avanzado, JavaScript y Node, tambien se encuentra agregado una carpeta para contener el trabajao final integrador que seria el e-comerce.
Esta tarjeta es para que esten al tanto de  lo que vamos a hacer, tengan en cuenta en responder por favor, gracias

**Comment by dwc1970** [comment]
Dante cargo las actividades de la clase de la primer semana de javascript

**Comment by dwc1970** [comment]
En el trnascurso del fin de semana voy a ir cargando las demas actividades de la primer semana de clases

**Comment by mzadante** [comment]
Tenes que avisarles a los demas dario eso es parte de la consigna gracias.

**Comment by mzadante** [comment]
Cerrado el scrum, abrazo muchachos
