### ISSUE TITLE
Dante, avanzar en el ecomerce

### ISSUE THREAD

**Issue by dwc1970** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#23]
Dante vos vas a ser el encargado de cargar la clase de Java avanzado

**Comment by mzadante** [comment]
ok

**Comment by mzadante** [comment]
Listo dario ya quedo añadida la clase 3 de java avanzado

**Comment by dwc1970** [comment]
Perfecto Dante, tu tarea de esta semana ha sido completada. 

🍬🍬🍬 tres caramelos de regalo !!
