### ISSUE TITLE
Andres e-comerce

### ISSUE THREAD

**Issue by dwc1970** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#24]
Andres  vos encargate de cargar la clase de la leccion de la semana de python y tambien agregar al repositorio tu avance en el proyecto de e-comerce

**Comment by andreswinck** [comment]
acabo de subir lo requerido

**Comment by dwc1970** [comment]
Andres, ya estaria completada tu tarea de la semana .

**Comment by dwc1970** [comment]
Perfecto Andres, tu tarea esta completa..!! 

🥟🥟🥟 tres empanadas de recompesa !!
