### ISSUE TITLE
Lucas Revision

### ISSUE THREAD

**Issue by dwc1970** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#26]
Lucas vos estas encargado de cargar la clase de javascript y los avances que tengas en e-comerce

**Comment by JereRiquero** [comment]
okk

**Comment by LucasSalinas** [comment]
buen dia, lo subo antes de mañana

**Comment by dwc1970** [comment]
Bueno, mañana ya estoy cerrando el scrum a las 16 horas

**Comment by LucasSalinas** [comment]
Dario buenas noches. Esta subida la tercera clase de JS

**Comment by dwc1970** [comment]
Bien Lucas... Gracias !!
