### ISSUE TITLE
Abel  E-comerce

### ISSUE THREAD

**Issue by dwc1970** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#27]
Abel carga los avances que tengas del proyecto e-comerce , fijate que no esten repetidos en las demas cargas asi a la hora de unirlo no hay confusion

**Comment by Abelino537** [comment]
Ok dario cuando lo termine te aviso

**Comment by Abelino537** [comment]
ya subi y ajuste todo

**Comment by dwc1970** [comment]
perfecto.
