### ISSUE TITLE
Carga de Python semana 1

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#3]
Bueno aqui esta donde bajar la clase de python , el sistema es el siguiente el que ya disponga de la clase para subirla tiene que avisarle al equipo que la subio primero que el resto, es para estar comunicados entre si siempre cualquier otra idea estoy dispuesto a escucharla

**Comment by JereRiquero** [comment]
Dante, ya subí la clase de Python y actualice el scrum...

**Comment by mzadante** [comment]
Gracias Jere recorda la proxima clase tendrias que esperar que otro suba el codigo primero y en el caso de que no lo haga el compañero se sube y se explica porque, cualquier duda contactame y te lo explico mejor

**Comment by JereRiquero** [comment]
Okey Dante, muchas gracias
