### ISSUE TITLE
JEREMIAS RIQUIERO (JS & PROYECTO)

### ISSUE THREAD

**Issue by Abelino537** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#35]
Hola Jeremías, tus tareas de esta semana son las siguientes:
1- Subir la clase 3 de Java Script.
2- Crear un archivo HTML dentro de la carpeta categorias-productos-html con el nombre "figuras-productos.html". (evita usar tildes, mayúsculas y espacios)
3- Linkear al HTML que creaste el archivo CSS "base.css"
4- Empezar a trabajar en el HTML colocando las imágenes que elegiste y agrégale estilo con CSS siguiendo el patrón de diseño del index.html.
Cualquier duda no dudes en escribirme.

**Comment by JereRiquero** [comment]
Dale Abel

**Comment by JereRiquero** [comment]
Abel, querido. Mañana el Andres arregla el código de JS

**Comment by JereRiquero** [comment]
Hay subí mi parte del proyecto

**Comment by Abelino537** [comment]
genial ya lo reviso

**Comment by Abelino537** [comment]
Código revisado, esta bien, a seguir trabajando así...
