### ISSUE TITLE
DARIO CARRIZO (PYTHON & PROYECTO)

### ISSUE THREAD

**Issue by Abelino537** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#36]
Hola Darío, tus tareas de esta semana son las siguientes:
1- Subir la clase 3 de Python.
2- Crear un archivo HTML dentro de la carpeta categorias-productos-html con el nombre "tazas-productos.html". (evita usar tildes, mayúsculas y espacios)
3- Linkear al HTML que creaste el archivo CSS "base.css"
4- Empezar a trabajar en el HTML colocando las imágenes que elegiste y agrégale estilo con CSS siguiendo el patrón de diseño del index.html.
5- Saca la carpeta ECO-dario de la carpeta principal y realiza la actividad de la tarjeta principal del Scrum.
Cualquier duda no dudes en escribirme.

**Comment by dwc1970** [comment]
ok, me pongo manos a la obra. Ante cualquie duda consulto por el grupo

**Comment by dwc1970** [comment]
Cargue la clase 3 de Pyton , queda pendiente cargar el codigo correpondiente al proyecto e-comerce

**Comment by Abelino537** [comment]
genial Dario, lo reviso mañana en la mañana ;)

**Comment by dwc1970** [comment]
Abel, cargue la carpeta con mi parte del proyecto integrador, me esta faltando cambiar la carpeta Eco-Dario. 
Me salta un error en el VCS y aún no lo puedo mover de lugar. Si lo podes hacer vos te lo agradeceria por que no me quiero mandar una macana.

**Comment by Abelino537** [comment]
ahi vi tu codigo de python, esta bien, agrega un comentario al readme de la carpeta de python

**Comment by Abelino537** [comment]
Bien tu trabajo de esta semana esta finalizado, a meterle garra y segui trabajando así...
