### ISSUE TITLE
FRANCO LARA (NODE & PROYECTO)

### ISSUE THREAD

**Issue by Abelino537** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#37]
Hola Franco, tus tareas de esta semana son las siguientes:
1- Subir la clase 4 de Node.
2- Crear un archivo HTML dentro de la carpeta categorias-productos-html con el nombre "armasdecoleccion-productos.html". (evita usar tildes, mayúsculas y espacios)
3- Linkear al HTML que creaste el archivo CSS "base.css"
4- Empezar a trabajar en el HTML colocando las imágenes que elegiste y agrégale estilo con CSS siguiendo el patrón de diseño del index.html.
Cualquier duda no dudes en escribirme...

**Comment by Chorifrann** [comment]
Subida la clase 4 de Node al readme ya que fue toda una clase teorica, ahora procedo con el html del proyecto ecommerce, salu2

**Comment by Abelino537** [comment]
Genial avisa cuando este subido

**Comment by Chorifrann** [comment]
Ahi lo subi, espero revision bro

**Comment by Abelino537** [comment]
bueno dale bro

**Comment by Abelino537** [comment]
tu parte de Node esta bien revisa lo del proyecto que te señale por el grupo

**Comment by Abelino537** [comment]
Ya revise todo tu código, esta bien hay que organizar las cajas en el siguiente scrum, segui así saludos...
