### ISSUE TITLE
ANDRES WINCKLER (PROYECTO)

### ISSUE THREAD

**Issue by Abelino537** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#39]
Hola Andrés tus tareas de esta semana son las siguientes:
1- Crear un archivo HTML dentro de la carpeta categorias-productos-html con el nombre "simpsonmania-productos.html". (evita usar tildes, mayúsculas y espacios)
2- Linkear al HTML que creaste el archivo CSS "base.css"
3- Empezar a trabajar en el HTML colocando las imágenes que elegiste y agrégale estilo con CSS siguiendo el patrón de diseño del index.html. 
Cualquier duda no dudes en escribirme...

**Comment by andreswinck** [comment]
Perfecto Abel, empiezo con eso. Gracias

**Comment by andreswinck** [comment]
Creada la página, solo resta que  des tu visto bueno

**Comment by Abelino537** [comment]
genial Andrés mañana lo reviso

**Comment by Abelino537** [comment]
Hola Andrés, te pido que revises el codigo que subiste porque tiene algunos errores, avisame cuando lo hagas así veo bien como quedo

**Comment by Abelino537** [comment]
no es necesario que sea para hoy, cualquier cosa avisame

**Comment by Abelino537** [comment]
buenas tardes Andrés tu código esta bien, sigamos trabajando así...
