### ISSUE TITLE
DANTE NICO MARTINEZ (PROYECTO)

### ISSUE THREAD

**Issue by Abelino537** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#40]
Hola Dante tus tareas de esta semana son las siguientes:
1- Crear un archivo HTML dentro de la carpeta categorias-productos-html con el nombre "comics-productos.html". (evita usar tildes, mayúsculas y espacios)
2- Linkear al HTML que creaste el archivo CSS "base.css"
3- Empezar a trabajar en el HTML colocando las imágenes que elegiste y agrégale estilo con CSS siguiendo el patrón de diseño del index.html. 
Cualquier duda no dudes en escribirme...

**Comment by mzadante** [comment]
joya Abel trabajando en ello

**Comment by mzadante** [comment]
Listo abel lo mio habria que ponerse de acuedo con las imagenes en las categorias que todas queden iguales en las propiedades css, miralo y despues me decis por si hay que modificar algo

**Comment by Abelino537** [comment]
hola dante bueno dale genial, lo vamos a revisar en la llamada de hoy

**Comment by Abelino537** [comment]
Codigo revisado, esta bien, falto que cambiaras la correccion de la imagen, fuera de eso buen trabajo....
