### ISSUE TITLE
Js y proyecto (Andres)

### ISSUE THREAD

**Issue by Chorifrann** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#44]
Esta semana te toca la clase de JS y realiza los cambios nombrados en "Importante" a tu html de la categoria que subiste.

**Comment by andreswinck** [comment]
Perfecto, ya estoy avanzando en eso...

**Comment by andreswinck** [comment]
Terminado el e-commerce en JS y el estilado del proyecto integrador
esperando se dé el visto bueno del SCRUM MASTER

**Comment by Chorifrann** [comment]
Verificado, esta todo perfecto.
