### ISSUE TITLE
Java y proyecto (Dante)

### ISSUE THREAD

**Issue by Chorifrann** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#45]
Esta semana te toca la clase de Java y realiza los cambios nombrados en "Importante" a tu html de la categoria que subiste.

**Comment by mzadante** [comment]
Dale querido comenzando

**Comment by mzadante** [comment]
Listo Franco quedo subida la clase 5 de java con spring, paso a la sección de revisado y te consulto donde esta la parte esa que dice ("Importante" a tu html de la categoria que subiste) no estaria entiendo espero tu respuesta

**Comment by andreswinck** [comment]
Es la primera tarjeta del scrum Dante titulada IMPORTANTE
donde están los cambios que hay que hacerle a la WEB

**Comment by mzadante** [comment]
Gracias Andres, bien Franco ya quedo lista la pagina del ecomerce de los comics, se le agrego lo pedido en importante, abrazo dejo en revision cualquier problema estoy a disposicion!

**Comment by Chorifrann** [comment]
Perfecto Dante, esta todo correcto.
