### ISSUE TITLE
Carga de JavaScript semana 1

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#5]
Bueno aqui esta donde bajar la clase de JavaScript , el sistema es el siguiente el que ya disponga de la clase para subirla tiene que avisarle al equipo que la subio primero que el resto, es para estar comunicados entre si siempre cualquier otra idea estoy dispuesto a escucharla

**Comment by dwc1970** [comment]
Dante, ya esta cargada la actividad de javacript de la primer semana

**Comment by mzadante** [comment]
Dario cambia lo que cargastes a donde corresponde y estarias listo.

**Comment by mzadante** [comment]
Gracias Dario recorda la proxima clase tendrias que esperar que otro suba el codigo primero y en el caso de que no lo haga el compañero se sube y se explica porque cualquier duda contactame y te lo explico mejor

**Comment by dwc1970** [comment]
Se avisa al grupo en el Readme que ya se cargo la leccion 1 de Javascript donde se comienza el proyecto  para fin de semestres
