### ISSUE TITLE
Proyecto (Dario)

### ISSUE THREAD

**Issue by Chorifrann** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#50]
Realiza los cambios nombrados en "Importante" a tu html de la categoria que subiste.

**Comment by dwc1970** [comment]
Hice un cambio en el css , me queda ver el html

**Comment by dwc1970** [comment]
hice unos cambios en el codigo pero no funciona correctamente,  asi que voy a arreglarlo para ya integrarlo de forma correcta para el peoximo scrum con las tareas que correspondan.
