### ISSUE TITLE
AVISO

### ISSUE THREAD

**Issue by LucasSalinas** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#51]
Hola a todos, habiendo organizado hoy en llamada, decidimos extender el scrum hasta el 29 a las 00:00 hs.
Paso a dar las instrucciones de lo que debemos hacer:
1- Ir al archivo "productos.js" y agregar sus productos al final de las ultimas líneas.
2- En Id deben enumerar los productos de forma continua, por ej 1, 2, 3, 4...
3- En categoría escriban su categoría solo nombrándola, por ej: "Accesorios", "Remeras", etc.
4- Ahora mueven las imágenes de la categoría de sus productos a la nueva carpeta (Que contendrá todas las imágenes), llamada "productos-imágenes".
5- Por último, en "productos.js" escriben el directorio de la imagen en el apartado "producto-imagen".

Cualquier duda pregunten.

**Comment by mzadante** [comment]
ok dale lucas hoy a las 19 podria ser?

**Comment by mzadante** [comment]
arregle las carpeta de imagenes-productos estaba asi y quedo productos-imagens para que coincida con el json ademas cree mis 10 articulos en ese archivo json
