### ISSUE TITLE
Python y proyecto

### ISSUE THREAD

**Issue by LucasSalinas** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#52]
Hola Dario te toca la clase 4 de Python y los avances para el proyecto.

**Comment by dwc1970** [comment]
Hola Lucas, perfecto,  lo de payton lo cargo ahora lo del avance del E-commerce lo hago una vez que definamos en la reunion por dicord

**Comment by dwc1970** [comment]
Ya esta commiteada la clase de Python , faltaria los avances del E-commerce que se definira en la reunion de Discord

**Comment by LucasSalinas** [comment]
Hola Dario, revisado.
