### ISSUE TITLE
Java y proyecto

### ISSUE THREAD

**Issue by LucasSalinas** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#54]
Hola Abel te toca la clase 6 de Java y los avances para el proyecto.

**Comment by Abelino537** [comment]
ok te aviso cuando suba lo de java

**Comment by Abelino537** [comment]
ya termine de subir la clase y colabore con el proyecto

**Comment by LucasSalinas** [comment]
Hola Abel bien, terminado tu trabajo.
