### ISSUE TITLE
Proyecto (Dante)

### ISSUE THREAD

**Issue by LucasSalinas** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#56]
Hola Dante te toca seguir avanzando con el proyecto.

**Comment by mzadante** [comment]
dale querido dependiendo de la reunion de hoy vemos que hacemos

**Comment by mzadante** [comment]
Cree una nueva carpeta llamada tierraMedia alli dentro pasaremos en limpio el e-comerce del proyecto integrador

**Comment by mzadante** [comment]
arregle las carpeta de imagenes-productos estaba asi y quedo productos-imagens para que coincida con el json ademas cree mis 10 articulos en ese archivo json

**Comment by LucasSalinas** [comment]
gracias Dante, esta perfecto
