### ISSUE TITLE
Proyecto (Andres)

### ISSUE THREAD

**Issue by LucasSalinas** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#57]
Hola Andres te toca seguir avanzando con el proyecto

**Comment by andreswinck** [comment]
perfecto, sigo en eso

**Comment by andreswinck** [comment]
Hay que arreglar el JSON antes de poder seguir con el proyecto, avisame cuando esté completo

**Comment by LucasSalinas** [comment]
Bien hecho Andres
