### ISSUE TITLE
Dario realizar node y e-commerce

### ISSUE THREAD

**Issue by ezequielmariscal** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#63]

**Comment by ezequielmariscal** [comment]
Dario revisar lunes 25 de sept de node, subirlo y avanzar con el e-commerce

**Comment by dwc1970** [comment]
`

> Se` actulizo el repo de NodeJs con los ejecicios hasta el dia 27/09  

> falta realizar avances en el E-comerce , que se vera en la proxima reuncion de discord del grupo. #

**Comment by dwc1970** [comment]
La tarea asignada fue cargada.
