### ISSUE TITLE
lucas ponete una foto de perfil en github y avanzar con el e-commerce

### ISSUE THREAD

**Issue by ezequielmariscal** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#66]
Lucas te salvaste esta semana avanza con e-commerce ya sea tanto en un registe o un login o carrousel, si se te complica averiguar sobre como implementar saas

**Comment by ezequielmariscal** [comment]
El beta va a empezar a revisar los github te recomiendo q te pongas foto porque sino va mala nota... (consejito no mas)

**Comment by LucasSalinas** [comment]
Hola Eze ok
