### ISSUE TITLE
Abel avanzar con el e-commerce

### ISSUE THREAD

**Issue by ezequielmariscal** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#67]
te has sacado el comodin semanal asique no tienes tarea de la semana , pero si seguir avanzando en el e-commerce, averiguar sobre login, register, o carrusel a implementar

**Comment by Abelino537** [comment]
ok dale voy avisando de mis avances en el proyecto

**Comment by Abelino537** [comment]
avanzo con cosas del proyecto que se terminaran en el proximo scrum
