### ISSUE TITLE
Dante avanzar en el e-commerce

### ISSUE THREAD

**Issue by ezequielmariscal** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#68]
Querido dante sigue avanzando en el e-commerce, averiguar sobre login, register o carrusel.

**Comment by mzadante** [comment]
ok dale

**Comment by mzadante** [comment]
Cree en App.js el funcionamiento general del carrito, style-cart.css con los estilos del carrito, queda funcional salvo por 2 errores de visualizacion css que el abel se encargara

**Comment by mzadante** [comment]
Agrego comentarios, al codigo realizado anteriormente
