### ISSUE TITLE
Avanzar con documentación del e-commerce

### ISSUE THREAD

**Issue by andreswinck** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#75]
Ver si hay que hacer algo para BASES DE DATO con NATALIA LUCERO
si no hay tarea, ayudar a JEREMIAS con el readme del e-commerce

**Comment by dwc1970** [comment]
Yo me encargo de subir los codigos de Nodejs y Python  de esta semana

**Comment by dwc1970** [comment]
Commitie la clase de NodeJs " Fundamentos_Nodejs"  Hable con el Jere, voy a revisar lo que seria el diseño y hacer cambios si fuere necesario

**Comment by mzadante** [comment]
Bueno subi el primer pre release del ecomerce lo subi con pago y la conexion de la base local mysql, creo que hay que arreglar el footer y lanzarlo

**Comment by dwc1970** [comment]
Agrege al repositorio la sección "Nosotros" con las imagenes, css y html ..
