### ISSUE TITLE
Finalizar el proyecto integrador y subir clases de esta semana

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#78]
Hola muchachos, comienzo el scrum semanal, bueno hoy dependiendo de lo que de el Profe, hay que subir las clases vistas y tenemos que cordinar con la edicion y produccion del video del proyecto integrador si pueden hoy a las 19 horas nos juntamos por discord y terminamos de coordinar

**Comment by dwc1970** [comment]
ok..

**Comment by dwc1970** [comment]
Subo la clase de NodeJs CallbackHell

**Comment by JereRiquero** [comment]
Okey Dante, nos vemos a las 19hs

**Comment by andreswinck** [comment]
Ok, se graba video de la parte de la pasarela de pagos para comenzar a finalizar el proyecto

**Comment by mzadante** [comment]
Joya muy buen trabajo a todos
