### ISSUE TITLE
Aqui colocar el brief terminado

### ISSUE THREAD

**Issue by mzadante** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#9]
Aqui el encargado de subir lo que hicimos en discord tiene que subir al github a la carpeta del proyecto

**Comment by Chorifrann** [comment]
Cargado el brief del proyecto del e-commerce que armamos via llamada de discord en grupo.

[Brief.docx](https://github.com/CodeSystem2022/No-Code_CUARTO-SEMESTRE/files/12402154/Brief.docx)

**Comment by mzadante** [comment]
Bien franco tarea terminada entonces abrazo
