### ISSUE TITLE
Dante

### ISSUE THREAD

**Issue by dwc1970** [CodeSystem2022/No-Code_CUARTO-SEMESTRE#94]
Ir poniendo en las tarjetas el avance que han hecho en el video.

* qué seccion del codigo cometas .
* hacer una revison para ir corriigiendo detalles 
* Ir moviendo las tarjeta

**Comment by mzadante** [comment]
ya termine mi parte total del video dario con lo de la base de datos, alli arregle el readme del proyecto que no enlazaba con el brief
